In [1]:
import pandas as pd
import numpy as np
import pickle

In [37]:
df = pd.read_csv('data_zpyYWs0.csv')

In [38]:
df.head()

player_id   player_name runs_scored wickets runs_conceded catches  \
0          1   Pat Cummins         DNB       3            28       0   
1          2   Steve Smith         DNB       -             -       0   
2         10   Mitch Marsh          8*       1            19       1   
3         13  David Warner          20       -             -       0   
4          1   Pat Cummins         11*       1            73       0   

  stumpings   match_date                opposition  match_id  
0         0  19 Oct 2011  v South Africa Centurion         1  
1         0  19 Oct 2011  v South Africa Centurion         1  
2         0  19 Oct 2011  v South Africa Centurion         1  
3         0  19 Oct 2011  v South Africa Centurion         1  
4         0  23 Oct 2011   v South Africa Gqeberha         2

In [39]:
data = df.drop_duplicates(subset=['player_name'])

In [40]:
data.shape

(30, 10)

In [41]:
data = data.iloc[:,:2]

In [42]:
data = data.sort_values('player_id')

In [43]:
data

player_id          player_name
0            1          Pat Cummins
1            2          Steve Smith
263          3           Alex Carey
584          4          Josh Inglis
604          5          Sean Abbott
424          6   Marnus Labuschagne
576          7        Cameron Green
22           8       Josh Hazlewood
91           9          Travis Head
2           10          Mitch Marsh
17          11        Glenn Maxwell
82          12       Marcus Stoinis
3           13         David Warner
94          14           Adam Zampa
19          15      Mitchell Starc.
36          16         Rohit Sharma
191         17        Hardik Pandya
622         18         Shubman Gill
37          19          Virat Kohli
430         20         Shreyas Iyer
324         21             KL Rahul
292         22      Ravindra Jadeja
433         23       Shardul Thakur
193         24       Jasprit Bumrah
648         25       Mohammed Siraj
194         26        Kuldeep Yadav
38          27       Mohammed Shami
39          28  Ravichandran Ashwin
630         29         Ishan Kishan
631         30     Suryakumar Yadav

In [256]:
model = pickle.load(open('model_best_bat.pkl', 'rb'))

In [257]:
nbat = pd.read_csv('updated_nbat.csv')

In [258]:
nbat.iloc[289]

Unnamed: 0                                      289
Innings Player                            DA Warner
Innings Runs Scored                              74
date_month                                       10
Average Runs Last 5 Matches                    52.4
Average Strike rate Last 5 Matches             92.4
boundary_per_ball                          0.061856
Average Innings Minutes Batted 5 match         86.4
Average balls faced 5 match                    65.0
50s or 100s                                       1
order                                           2.0
style agg def tail                              2.0
home away                                       0.0
oppo                                            1.0
Name: 289, dtype: object

### Prediction

In [346]:
# id 1 
test_input = ['PJ Cummins',10,15.8,96.3,0.085,82,0,1,1,1,1]

In [347]:
pat_cummins = model.predict([test_input])[0]

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [348]:
pat_cummins

26.232511757311478

In [349]:
# id 2
test_input = ['SPD Smith',10,27.4,88.4,0.109,31,1,2,2,1,1]

In [350]:
steve_smith = model.predict([test_input])[0]

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [351]:
steve_smith

68.40740116065064

In [352]:
#id 3
test_input = ['A Carey',10,27.5,80.88,0.125,27,1,2,2,1,1]

In [353]:
alex_carry = model.predict([test_input])[0]-40

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [354]:
alex_carry

27.760870944002292

In [355]:
#id 4
test_input = ['Josh Inglis',10,24.4,64.2,0.14,20,1,2,1,1,1]

In [356]:
josh_inglin = model.predict([test_input])[0]-40

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [357]:
josh_inglin

31.124426871060223

In [358]:
#id 5

#test_input = ['Sean Abbote',1,36.6,84.6,0.2,37.0,0,2,1,0,1]
test_input = ['Sean Abbote',1,10.6,10.56,0.173,15,0,0,0,0,1]

In [359]:
sean_abbote = model.predict([test_input])[0]-20

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [360]:
sean_abbote

14.668954947050437

In [361]:
#id 6
test_input = ['Marnus Labuschagne',10,40.5,90,0.098,44.6,1,2,2,1,1]

In [362]:
labuschange = model.predict([test_input])[0]-40

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [363]:
labuschange

33.366238597950144

In [364]:
#id 7

test_input = ['Cameron Greene',10,15.4,68,0.0841,21.4,0,0,1,1,1]

In [365]:
green = model.predict([test_input])[0]-8

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [366]:
green

13.427241199839138

In [367]:
#id 8

test_input = ['Josh Hazlewood',10,7.2,50,0.1944,8,0,0,0,1,1]

In [368]:
hzelwood = model.predict([test_input])[0]-10

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [369]:
hzelwood

6.7290975099026085

In [370]:
#id 9

test_input = ['Travis Head',10,37,142,0.261,26,2,1,2,1,1]

In [371]:
head = model.predict([test_input])[0]-40

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [372]:
head

87.12597043939715

In [373]:
#id 10

test_input = ['Mitch Marsh',10,0,0,0,0,0,0,0,0,0]

In [374]:
m_marsh = model.predict([test_input])[0].round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [375]:
m_marsh

0.0

In [376]:
#id 11

test_input = ['Glenn Maxwell',10,10.8,80,0.0481,16,0,1,2,1,1]

In [377]:
maxwell = model.predict([test_input])[0].round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [378]:
maxwell

18.0

In [379]:
#id 12

test_input = ['Marcus Stoinis',10,19.8,125,0.1829,16.4,0,1,2,1,1]

In [380]:
stoins = model.predict([test_input])[0].round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [381]:
stoins

22.0

In [382]:
#id 13

test_input = ['David Warner',10,36.8,134,0.1931,29,2,2,2,1,1]

In [383]:
warner = model.predict([test_input])[0].round()-60

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [384]:
warner

72.0

In [385]:
#id 14
test_input = ['Adam Zampa',10,6.2,60,0.1111,7.2,0,0,0,1,1]

In [386]:
zampa = model.predict([test_input])[0].round()-10

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [387]:
zampa

1.0

In [388]:
#id 15

test_input = ['Mitchell Starc.',10,10.6,30,0.071,14,0,0,0,1,1]

In [389]:
starc= model.predict([test_input])[0].round()-10

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [390]:
starc

10.0

In [391]:
#id 16

test_input = ['Rohit Sharma',10,52.8,110,0.1860,43,1,2,2,1,1]

In [392]:
rohit= model.predict([test_input])[0].round()-10

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [393]:
rohit

56.0

In [394]:
#id 17

test_input = ['Hardik Pandya',10,34.8,75.76,0.0939,36.2,1,1,2,1,1]

In [395]:
hardik= model.predict([test_input])[0].round()-40

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [306]:
hardik

30.0

In [307]:
#18

test_input = ['Shubman Gill',10,69,106.2,0.1183,67.6,2,2,1,0,0]

In [308]:
gill= model.predict([test_input])[0].round()-60

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [309]:
gill

66.0

In [310]:
#id 19

test_input = ['Virat Kohli',10,47.8,60.4,0.0894,49.2,1,2,1,1,1]

In [311]:
koholi= model.predict([test_input])[0].round()-40

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [312]:
koholi

38.0

In [313]:
#id 20

test_input = ['Shreyas Iyer',10,41.6,60,0.0012,36.4,1,1,1,1,1]

In [314]:
iyyer= model.predict([test_input])[0].round()-40

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [315]:
iyyer

22.0

In [316]:
#id 21

test_input = ['KL Rahul',10,38.8,90,0.0794,42.8,1,1,1,1,1]

In [317]:
rahul= model.predict([test_input])[0].round()-25

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [318]:
rahul

40.0

In [319]:
# id 22

test_input = ['Ravindra Jadeja',10,12.5,70,0.0122,16.4,0,0,1,1,1]

In [320]:
jadeja= model.predict([test_input])[0].round()-10

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [321]:
jadeja

11.0

In [322]:
#id 23

test_input = ['Shardul Thakur',10,11.2,60,0.0842,11.8,0,0,1,1,1]

In [323]:
thakur= model.predict([test_input])[0].round()-10

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [324]:
thakur

8.0

In [325]:
#id 24

test_input = ['Jasprit Bumrah',10,5,37,0.0042,5,0,0,0,1,1]

In [326]:
bumrah= model.predict([test_input])[0].round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [327]:
bumrah

2.0

In [328]:
#id 25

test_input = ['Mohammed Siraj',10,1,10,0.0042,5,0,0,0,1,1]

In [329]:
siraj= model.predict([test_input])[0].round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [330]:
siraj

2.0

In [331]:
#id 26

test_input = ['Kuldeep Yadav',10,1,0,0.0042,5,0,0,0,1,1]

In [332]:
kuldeep= model.predict([test_input])[0].round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [333]:
kuldeep

2.0

In [334]:
#id 27

test_input = ['Mohammed Shami',10,0,0,0.0042,1,0,0,0,1,1]

In [335]:
shami= model.predict([test_input])[0].round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [336]:
shami

-0.0

In [337]:
#id 28

test_input = ['Ravichandran Ashwin',10,38.8,90,0.0794,42.8,0,1,1,1,1]

In [338]:
ashwin = model.predict([test_input])[0].round()-15

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [339]:
ashwin

18.0

In [340]:
#id 29

test_input = ['Ishan Kishan',10,38.8,90,0.0794,42.8,0,1,1,1,1]

In [341]:
kishan = model.predict([test_input])[0].round()-10

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [342]:
kishan

23.0

In [343]:
#id 30

test_input = ['Suryakumar Yadav',10,38.2,90,0.0794,30,0,1,1,1,1]

In [344]:
suryakumar = model.predict([test_input])[0].round()-10

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [345]:
suryakumar

25.0

In [396]:
score = np.array([pat_cummins,steve_smith,alex_carry,josh_inglin,sean_abbote,labuschange,green,hzelwood,head,
        m_marsh,maxwell,stoins,warner,zampa,starc,rohit,hardik,gill,koholi,iyyer,rahul,jadeja,thakur,bumrah,siraj,
        kuldeep,shami,ashwin,kishan,suryakumar])

# bowling

In [2]:
model = pickle.load(open('model_best_ball.pkl', 'rb'))

In [3]:
nball = pd.read_csv('updated_nball.csv')

In [4]:
nball['Innings Player'].unique()

array(['RA Jadeja', 'R Ashwin', 'JR Hazlewood', 'MA Starc', 'PJ Cummins',
       'Mohammed Shami', 'SA Abbott', 'MP Stoinis', 'JJ Bumrah',
       'A Zampa', 'HH Pandya', 'Kuldeep Yadav', 'SN Thakur',
       'Mohammed Siraj', 'ZE Green'], dtype=object)

In [49]:
nbat = pd.read_csv('nbat.csv')

In [50]:
nbat['Innings Player'].unique()

array(['DA Warner', 'SPD Smith', 'MP Stoinis', 'TM Head', 'M Labuschagne',
       'MR Marsh', 'GJ Maxwell', 'AT Carey', 'PJ Cummins', 'A Zampa',
       'JR Hazlewood', 'SA Abbott', 'RG Sharma', 'V Kohli', 'KL Rahul',
       'SS Iyer', 'RA Jadeja', 'HH Pandya', 'R Ashwin', 'Mohammed Shami',
       'SN Thakur', 'Kuldeep Yadav', 'JJ Bumrah', 'Shubman Gill',
       'Mohammed Siraj', 'MA Starc'], dtype=object)

In [5]:
nball.head()

Unnamed: 0 Innings Player  Innings Wickets Taken  \
0           0      RA Jadeja                      0   
1           1      RA Jadeja                      0   
2           2      RA Jadeja                      0   
3           3      RA Jadeja                      0   
4           4      RA Jadeja                      0   

   last_five_matches_wickets  Average over bowled in 5 mts  \
0                        0.0                           7.0   
1                        0.0                           7.0   
2                        0.0                           7.0   
3                        0.0                           7.0   
4                        0.0                           7.0   

   total maiden over last 5 mts  Average runs conceed in last 5 mts  \
0                           0.0                                34.0   
1                           0.0                                34.0   
2                           0.0                                34.0   
3                           1.0                                34.0   
4                           2.0                                34.0   

   Average economy last 5 mts  match year 2018 or not  home away  oppo  \
0                        4.85                     0.0        0.0   0.0   
1                        4.85                     0.0        0.0   0.0   
2                        4.85                     0.0        0.0   0.0   
3                        4.85                     0.0        0.0   0.0   
4                        4.85                     0.0        0.0   0.0   

   fast or spin  
0           0.0  
1           0.0  
2           0.0  
3           0.0  
4           0.0

In [25]:
#test_input = ['A Zampa',10,9.4,3,331,6.56,1,1,1,0]

In [26]:
model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([2.])

In [32]:
#nball.corr(numeric_only=True)['Innings Wickets Taken']

In [44]:
data

player_id          player_name
0            1          Pat Cummins
1            2          Steve Smith
263          3           Alex Carey
584          4          Josh Inglis
604          5          Sean Abbott
424          6   Marnus Labuschagne
576          7        Cameron Green
22           8       Josh Hazlewood
91           9          Travis Head
2           10          Mitch Marsh
17          11        Glenn Maxwell
82          12       Marcus Stoinis
3           13         David Warner
94          14           Adam Zampa
19          15      Mitchell Starc.
36          16         Rohit Sharma
191         17        Hardik Pandya
622         18         Shubman Gill
37          19          Virat Kohli
430         20         Shreyas Iyer
324         21             KL Rahul
292         22      Ravindra Jadeja
433         23       Shardul Thakur
193         24       Jasprit Bumrah
648         25       Mohammed Siraj
194         26        Kuldeep Yadav
38          27       Mohammed Shami
39          28  Ravichandran Ashwin
630         29         Ishan Kishan
631         30     Suryakumar Yadav

In [46]:
#id 1
test_input= ['PJ Cummins',9,8,3,42.5,5.12,1,1,1,0]

In [47]:
cummins_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [48]:
cummins_b

array([2.])

In [51]:
#id2
test_input= ['SPD Smith',0,0,0,0,0,1,1,1,0]

In [54]:
smith_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [55]:
smith_b

array([0.])

In [56]:
#id 3

test_input= ['Alex Carey',0,0,0,0,0,1,1,1,0]

In [57]:
carry_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [58]:
carry_b

array([0.])

In [60]:
#id 4

test_input= ['Josh Inglis',0,0,0,0,0,1,1,1,0]

In [61]:
inglis_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [62]:
inglis_b

array([0.])

In [70]:
#id 5

test_input= ['SA Abbott',1,40,2,70,8,1,1,1,1]

In [71]:
abbott_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [72]:
abbott_b

array([2.])

In [73]:
#id6

test_input= ['Marnus Labuschagne',0,0,2,0,8,1,1,1,1]

In [76]:
labuchegn_b = model.predict([test_input]).round()+1

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [77]:
labuchegn_b

array([0.])

In [79]:
#id7

test_input= ['ZE Green',0,0,2,0,8,1,1,1,1]

In [84]:
green_b = model.predict([test_input]).round()+1

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [85]:
green_b

array([0.])

In [125]:
#id8

test_input= ['JR Hazlewood',8,9,2,60,6,1,1,1,1]

In [126]:
hzelwood_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [127]:
hzelwood_b

array([2.])

In [92]:
#id 9

test_input= ['Travis Head',0,0,0,60,6,1,1,1,1]

In [97]:
head_b = model.predict([test_input]).round()*-1

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [98]:
head_b

array([-0.])

In [99]:
#id 10

test_input= ['Mitch Marsh',0,0,0,60,6,1,1,1,1]

In [121]:
marsh_b = model.predict([test_input]).round()*-1

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [122]:
marsh_b

array([0.])

In [114]:
#id 11
test_input= ['Glenn Maxwell',0,0,0,60,6,1,1,1,1]

In [119]:
maxwell_b = model.predict([test_input]).round()*-1

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [120]:
maxwell_b

array([0.])

In [134]:
#id 12

test_input= ['MP Stoinis',1,0,0,5,44,5,5,1,1]

In [143]:
stoins_b = model.predict([test_input]).round()+4

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [144]:
stoins_b

array([0.])

In [151]:
#id 13

test_input= ['David Warner',0,0,0,5,40,5,5,1,1]

In [152]:
warner_b = model.predict([test_input]).round()+4

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [153]:
warner_b

array([0.])

In [162]:
#id 14

test_input= ['A Zampa',5,9,2,60,6,1,1,1,0]

In [163]:
zampa_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [164]:
zampa_b

array([1.])

In [165]:
#id15

test_input= ['MA Starc',8,9,2,60,6,1,1,1,0]

In [166]:
starc_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [167]:
starc_b

array([2.])

In [168]:
#id 16
test_input= ['Rohit Sharma',0,0,0,0,0,1,1,1,0]

In [169]:
rohit_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [170]:
rohit_b

array([0.])

In [175]:
#id 17

test_input= ['Hardik Pandya',2,6,2,0,0,1,1,1,1]

In [176]:
hardik_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [177]:
hardik_b

array([1.])

In [178]:
#id 18

test_input= ['Shubman Gill',0,0,0,0,0,1,1,1,0]

In [179]:
shuban_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [181]:
shuban_b

array([0.])

In [182]:
#id 19

test_input= ['Virat Kohli',0,0,0,0,0,1,1,1,0]

In [183]:
virat_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [184]:
virat_b

array([0.])

In [185]:
#20

test_input= ['Shreyas Iyer',0,0,0,0,0,1,1,1,0]

In [186]:
iyyer_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [187]:
iyyer_b

array([0.])

In [188]:
#id21

test_input= ['KL Rahul',0,0,0,0,0,1,1,1,0]

In [189]:
rahul_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [190]:
rahul_b

array([0.])

In [191]:
#id22

test_input= ['Ravindra Jadeja',8,9,2,60,6,1,1,1,0]

In [193]:
jadeja_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [194]:
jadeja_b

array([2.])

In [195]:
#id23

test_input= ['Shardul Thakur',5,9,2,60,6,1,1,1,0]

In [196]:
thakur_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [197]:
thakur_b

array([1.])

In [207]:
#id24
test_input= ['Jasprit Bumrah',8,9,2,60,6,1,1,1,0]

In [208]:
bumrah_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [209]:
bumrah_b

array([2.])

In [222]:
#id25

test_input= ['Mohammed Siraj',20,9,2,60,6,1,1,1,0]

In [223]:
siraj_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [224]:
siraj_b

array([3.])

In [226]:
#id26
test_input= ['Kuldeep Yadav',2,9,2,60,6,1,1,1,0]

In [230]:
kuldeep_b = model.predict([test_input]).round()-1

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [231]:
kuldeep_b

array([0.])

In [232]:
#id27

test_input= ['SMohammed Shami',5,9,2,60,6,1,1,1,0]

In [237]:
shami_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [238]:
shami_b

array([1.])

In [244]:
#id28

test_input= ['Ravichandran Ashwin',5,9,2,60,6,1,1,1,0]

In [245]:
aswhin_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [246]:
aswhin_b

array([1.])

In [247]:
#id29

test_input= ['Ishan Kishan',0,0,0,0,0,1,1,1,0]

In [248]:
kishan_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [250]:
kishan_b

array([0.])

In [251]:
#id30

test_input= ['suryakumar yadav',0,0,0,0,0,1,1,1,0]

In [252]:
yadav_b = model.predict([test_input]).round()

E:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [397]:
scores_b =np.array([cummins_b,smith_b,carry_b,inglis_b,abbott_b,labuchegn_b,green_b,hzelwood_b,
          head_b*-1,marsh_b,maxwell_b,stoins_b,warner_b,zampa_b,starc_b,rohit_b,hardik_b,
          shuban_b,virat_b,iyyer_b,rahul_b,jadeja_b,thakur_b,bumrah_b,siraj_b,kuldeep_b,
          shami_b,aswhin_b,kishan_b,yadav_b])

In [399]:
sample=pd.read_csv(r'C:\Users\Mrunmay\OneDrive\Desktop\sample_submission_Gk1Mne1.csv')

In [400]:
sample.head()

player_id  runs  wickets
0          1    30        2
1          2    24        0
2          3    45        1
3          4     5        2
4          5     9        0

In [401]:
idp = data['player_id'].values

In [413]:
final_data = pd.DataFrame()

In [414]:
final_data.insert(loc=0,column="player_id",value=idp)

In [415]:
final_data.insert(loc=1,column="runs",value=score)

In [420]:
final_data['runs'] = final_data['runs'].astype('int32')

In [417]:
final_data.insert(loc=2,column="wickets",value=scores_b)

In [422]:
final_data['wickets'] = final_data['wickets'].astype('int32')

In [423]:
final_data

player_id  runs  wickets
0           1    26        2
1           2    68        0
2           3    27        0
3           4    31        0
4           5    14        2
5           6    33        0
6           7    13        0
7           8     6        2
8           9    87        0
9          10     0        0
10         11    18        0
11         12    22        0
12         13    72        0
13         14     1        1
14         15    10        2
15         16    56        0
16         17    30        1
17         18    66        0
18         19    38        0
19         20    22        0
20         21    40        2
21         22    11        2
22         23     8        1
23         24     2        2
24         25     2        3
25         26     2        0
26         27     0        1
27         28    18        1
28         29    23        0
29         30    25        0

In [424]:
final_data.to_csv('final_submission.csv')

# END